#!/bin/sh

changed=0
rsync_out=$(rsync -aiz -e "ssh -i '{{ certbot.lookup.sync_certs_ssh_keyfile }}'" certsync@{{ certbot.sync_certs.from }}:* {{ certbot.sync_certs.to }}/)

if [ $? -eq 0 ]; then
    if [ -n "${RSYNC_COMMAND}" ]; then
        changed=1
    fi
else
    exit 1
fi

if [ $changed -eq 1 ]; then
{%- if "nginx" | which %}
    systemctl reload nginx
{%- endif %}
{%- if "semanage" | which %}
    restorecon -R '{{ certbot.sync_certs.to }}'
{%- endif %}
fi
